// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhP4zBNCjVzPzR3ZujYLiIcbHLbuFyLsQ',
    appId: '1:110761656450:web:04d909bddc4c0ff9fc749b',
    messagingSenderId: '110761656450',
    projectId: 'brewtrade-f1cf5',
    authDomain: 'brewtrade-f1cf5.firebaseapp.com',
    storageBucket: 'brewtrade-f1cf5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGcjpu3rkZMi7uFcwdnFoTm0NSajpAvls',
    appId: '1:110761656450:android:7fca15e849d03d9cfc749b',
    messagingSenderId: '110761656450',
    projectId: 'brewtrade-f1cf5',
    storageBucket: 'brewtrade-f1cf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhJWl7i38VwP_qrRz1G5Sqa_D-_AV2IGA',
    appId: '1:110761656450:ios:982299d223368777fc749b',
    messagingSenderId: '110761656450',
    projectId: 'brewtrade-f1cf5',
    storageBucket: 'brewtrade-f1cf5.firebasestorage.app',
    iosBundleId: 'com.example.brewtradeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhJWl7i38VwP_qrRz1G5Sqa_D-_AV2IGA',
    appId: '1:110761656450:ios:982299d223368777fc749b',
    messagingSenderId: '110761656450',
    projectId: 'brewtrade-f1cf5',
    storageBucket: 'brewtrade-f1cf5.firebasestorage.app',
    iosBundleId: 'com.example.brewtradeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhP4zBNCjVzPzR3ZujYLiIcbHLbuFyLsQ',
    appId: '1:110761656450:web:9d96f6c19e246c8dfc749b',
    messagingSenderId: '110761656450',
    projectId: 'brewtrade-f1cf5',
    authDomain: 'brewtrade-f1cf5.firebaseapp.com',
    storageBucket: 'brewtrade-f1cf5.firebasestorage.app',
  );
}
